### ISSUE TITLE
Class "FFI" not found 

### ISSUE THREAD

**Issue by JamorMoussa** [ankane/libmf-php#1]
Hi @ankane, 

I was looking for a library that makes the matrix factorization in the context of recommendation systems in PHP/Laravel, and I just found **libmf-php**. I followed the setup instructions, but I got the `Class "FFI" not found ` issue. If can provide any help.

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <?php

        $data = new Libmf\Matrix();
        $data->push(0, 0, 5.0);
        $data->push(0, 2, 3.5);
        $data->push(1, 1, 4.0);

        $model = new Model();

        $model->fit($data);

        print_r($model->predict(2, 0));
?>
</body>
</html>
```
![image](https://github.com/user-attachments/assets/745f7a50-7b65-49c9-a7aa-2dcae4179196)

**Comment by ankane** [comment]
Hi @JamorMoussa, it looks like your PHP installation may not have FFI enabled ([docs](https://www.php.net/manual/en/book.ffi.php)).
